<div style="background-color: ##000080;font-weight:bold;font-family:segoe ui;font-size:20px;color:white;padding:10px;line-height:1.3;text-align:left;border-radius: 10px;">
<div align="center">
Pós-graduação Lato Sensu em Ciência de Dados e Big Data - PUC MG
</div>

## Processamento/Tratamentos de Dados

In [1]:
# Importando Bibliotecas
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Carregando a base
conf_df = pd.read_csv('tcc_conformidade.csv', dtype={ 'cnae_classe': 'string'}, sep=';', decimal =',')
conf_df.head()

,setor,cnae_classe,situacao_cadastral,natureza_juridica,grande_empresa,obrigacoes_acessorias,obrigacao_principal,atuacao_fiscal,analise_comparativa,consistencia,comercio_exterior,conformidade,impacto
0,01000 - Instituicoes Financeiras e de Seguros,64221,Ativa,Entidades empresariais,Sim,0.8862,0.9575,0.990,0.5106,0.9237,0.7857,0.8875,Muito Alto
1,01000 - Instituicoes Financeiras e de Seguros,64221,Ativa,Entidades empresariais,Sim,0.9059,0.9717,1.000,0.5556,0.9483,1.0000,0.9272,Muito Alto
2,01000 - Instituicoes Financeiras e de Seguros,64930,Ativa,Entidades empresariais,Sim,0.9885,0.9975,1.000,0.5203,0.6413,1.0000,0.8430,Muito Alto
3,08001 - Automoveis,45307,Ativa,Entidades empresariais,Sim,1.0000,0.9286,1.000,0.4536,0.8905,1.0000,0.9039,Moderado
4,08001 - Automoveis,64620,Ativa,Entidades empresariais,Sim,1.0000,0.8800,0.963,0.4444,0.9494,1.0000,0.9045,Muito Baixo

In [3]:
#Verificando colunas e tipos atribuídos
print('Base de Dados: {} linhas e {} colunas'.format(len(conf_df), len(conf_df.columns)),'\n\n')
conf_df.info()

Base de Dados: 8392 linhas e 13 colunas


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8392 entries, 0 to 8391
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   setor                  8392 non-null   object
 1   cnae_classe            8392 non-null   string
 2   situacao_cadastral     8392 non-null   object
 3   natureza_juridica      8392 non-null   object
 4   grande_empresa         8392 non-null   object
 5   obrigacoes_acessorias  8392 non-null   float64
 6   obrigacao_principal    8392 non-null   float64
 7   atuacao_fiscal         8392 non-null   float64
 8   analise_comparativa    8392 non-null   float64
 9   consistencia           8392 non-null   float64
 10  comercio_exterior      8392 non-null   float64
 11  conformidade           8392 non-null   float64
 12  impacto                8392 non-null   object
dtypes: float64(7), object(5), string(1)
memory usage: 852.4+ KB

In [4]:
# Extraindo código e descrição da coluna setor
setor = conf_df.setor

setor_cod=[]
setor_desc=[]

for i in range(0,len(setor)):
    setor_partes=setor[i].split(' ',2)
    setor_cod.append(setor_partes[0][0:4]+setor_partes[0][4])
    setor_desc.append(setor_partes[2])
    
setor_df=pd.DataFrame(list(zip(setor_cod, setor_desc)), columns = ['setor_cod', 'setor_desc'])
setor_df.head()

  setor_cod                             setor_desc
0     01000  Instituicoes Financeiras e de Seguros
1     01000  Instituicoes Financeiras e de Seguros
2     01000  Instituicoes Financeiras e de Seguros
3     08001                             Automoveis
4     08001                             Automoveis

In [5]:
# Concatenando Dataframes
conf_df = pd.concat([setor_df, conf_df], axis = 1)
conf_df.head()

,setor_cod,setor_desc,setor,cnae_classe,situacao_cadastral,natureza_juridica,grande_empresa,obrigacoes_acessorias,obrigacao_principal,atuacao_fiscal,analise_comparativa,consistencia,comercio_exterior,conformidade,impacto
0,01000,Instituicoes Financeiras e de Seguros,01000 - Instituicoes Financeiras e de Seguros,64221,Ativa,Entidades empresariais,Sim,0.8862,0.9575,0.990,0.5106,0.9237,0.7857,0.8875,Muito Alto
1,01000,Instituicoes Financeiras e de Seguros,01000 - Instituicoes Financeiras e de Seguros,64221,Ativa,Entidades empresariais,Sim,0.9059,0.9717,1.000,0.5556,0.9483,1.0000,0.9272,Muito Alto
2,01000,Instituicoes Financeiras e de Seguros,01000 - Instituicoes Financeiras e de Seguros,64930,Ativa,Entidades empresariais,Sim,0.9885,0.9975,1.000,0.5203,0.6413,1.0000,0.8430,Muito Alto
3,08001,Automoveis,08001 - Automoveis,45307,Ativa,Entidades empresariais,Sim,1.0000,0.9286,1.000,0.4536,0.8905,1.0000,0.9039,Moderado
4,08001,Automoveis,08001 - Automoveis,64620,Ativa,Entidades empresariais,Sim,1.0000,0.8800,0.963,0.4444,0.9494,1.0000,0.9045,Muito Baixo

In [6]:
# Removendo Colunas desnecessárias
conf_df = conf_df.drop(columns=['setor','setor_desc','grande_empresa'])
print('Base de Dados: {} linhas e {} colunas'.format(len(conf_df), len(conf_df.columns)),'\n\n')
conf_df.info()

Base de Dados: 8392 linhas e 12 colunas


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8392 entries, 0 to 8391
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   setor_cod              8392 non-null   object
 1   cnae_classe            8392 non-null   string
 2   situacao_cadastral     8392 non-null   object
 3   natureza_juridica      8392 non-null   object
 4   obrigacoes_acessorias  8392 non-null   float64
 5   obrigacao_principal    8392 non-null   float64
 6   atuacao_fiscal         8392 non-null   float64
 7   analise_comparativa    8392 non-null   float64
 8   consistencia           8392 non-null   float64
 9   comercio_exterior      8392 non-null   float64
 10  conformidade           8392 non-null   float64
 11  impacto                8392 non-null   object
dtypes: float64(7), object(4), string(1)
memory usage: 786.9+ KB

In [7]:
# Ajustando Tipo da Coluna, conforme base original
tipo_coluna = {'setor_cod': 'string',
               'situacao_cadastral': 'string',
               'natureza_juridica': 'string',
               'impacto': 'string'}
conf_df = conf_df.astype(tipo_coluna)
conf_df.dtypes

setor_cod                 string
cnae_classe               string
situacao_cadastral        string
natureza_juridica         string
obrigacoes_acessorias    float64
obrigacao_principal      float64
atuacao_fiscal           float64
analise_comparativa      float64
consistencia             float64
comercio_exterior        float64
conformidade             float64
impacto                   string
dtype: object

In [8]:
# Verificando as colunas de Dimensão e Conformidade (valores entre 0 e 1)
obrigacoes_acessorias_0=conf_df.loc[conf_df['obrigacoes_acessorias'] < 0].empty  
obrigacoes_acessorias_1=conf_df.loc[conf_df['obrigacoes_acessorias'] > 1].empty  
obrigacao_principal_0=conf_df.loc[conf_df['obrigacao_principal'] < 0].empty  
obrigacao_principal_1=conf_df.loc[conf_df['obrigacao_principal'] > 1].empty  
atuacao_fiscal_0=conf_df.loc[conf_df['atuacao_fiscal'] < 0].empty  
atuacao_fiscal_1=conf_df.loc[conf_df['atuacao_fiscal'] > 1].empty  
analise_comparativa_0=conf_df.loc[conf_df['analise_comparativa'] < 0].empty  
analise_comparativa_1=conf_df.loc[conf_df['analise_comparativa'] > 1].empty  
consistencia_0=conf_df.loc[conf_df['consistencia'] < 0].empty  
consistencia_1=conf_df.loc[conf_df['consistencia'] > 1].empty  
comercio_exterior_0=conf_df.loc[conf_df['comercio_exterior'] < 0].empty  
comercio_exterior_1=conf_df.loc[conf_df['comercio_exterior'] > 1].empty  
conformidade_0=conf_df.loc[conf_df['conformidade'] < 0].empty   
conformidade_1=conf_df.loc[conf_df['conformidade'] > 1].empty   

print('Obrigações Acessórias 0 - {:}'.format(obrigacoes_acessorias_0))
print('Obrigações Acessórias 1 - {:}'.format(obrigacoes_acessorias_1))
print('Obrigação Principal 0 - {:}'.format(obrigacao_principal_0))
print('Obrigação Principal 1 - {:}'.format(obrigacao_principal_1))
print('Atuação Fiscal 0 - {:}'.format(atuacao_fiscal_0))
print('Atuação Fiscal 1 - {:}'.format(atuacao_fiscal_1))
print('Análise Comparativa 0 - {:}'.format(analise_comparativa_0))
print('Análise Comparativa 1 - {:}'.format(analise_comparativa_1))
print('Consistência 0 - {:}'.format(consistencia_0))
print('Consistência 1 - {:}'.format(consistencia_1))
print('Comércio Exterior 0 - {:}'.format(comercio_exterior_0))
print('Comércio Exterior 1 - {:}'.format(comercio_exterior_1))
print('Conformidade 0 - {:}'.format(conformidade_0))
print('Conformidade 1 - {:}'.format(conformidade_1))

Obrigações Acessórias 0 - True
Obrigações Acessórias 1 - True
Obrigação Principal 0 - True
Obrigação Principal 1 - True
Atuação Fiscal 0 - True
Atuação Fiscal 1 - True
Análise Comparativa 0 - True
Análise Comparativa 1 - True
Consistência 0 - True
Consistência 1 - True
Comércio Exterior 0 - True
Comércio Exterior 1 - True
Conformidade 0 - True
Conformidade 1 - True

In [9]:
conf_df.describe()

,obrigacoes_acessorias,obrigacao_principal,atuacao_fiscal,analise_comparativa,consistencia,comercio_exterior,conformidade
count,8392.000000,8392.000000,8392.000000,8392.000000,8392.000000,8392.000000,8392.000000
mean,0.902123,0.900645,0.950119,0.552640,0.777083,0.915417,0.844255
std,0.096729,0.118997,0.083246,0.109457,0.169526,0.108004,0.066840
min,0.000000,0.277700,0.339700,0.111100,0.034800,0.427600,0.473300
25%,0.863075,0.843000,0.929000,0.444400,0.647275,0.821775,0.802000
50%,0.928300,0.948000,1.000000,0.555600,0.824750,1.000000,0.848300
75%,0.975600,0.997000,1.000000,0.666700,0.926125,1.000000,0.898000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.997600

In [10]:
# Verificando Dados ausentes (missing data)
conf_df.isnull().sum()

setor_cod                0
cnae_classe              0
situacao_cadastral       0
natureza_juridica        0
obrigacoes_acessorias    0
obrigacao_principal      0
atuacao_fiscal           0
analise_comparativa      0
consistencia             0
comercio_exterior        0
conformidade             0
impacto                  0
dtype: int64

In [11]:
# Salvando Dataset após processamento/tratamento
conf_df.to_csv('tcc_conformidade_2.csv', index=False)